version: '3.8'

services:
  os_lab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: os_lab_container
    volumes:
      - ./lab01:/home/lab01
      - ./lab02:/home/lab02
    tty: true
    stdin_open: true